# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1118491794bf1d9bd82f57fb259f90fee96fdace420a06ed4bd479c6db42baca4fde0c82034f905bb976cec54794cd08defd1610a9544047bbbb1239ecb55f57

test:
  secret_key_base: b67fa6b5345715156fe618f19a6e1a2bc6dfbf8dc94a76ff53086b5e806922b3a956643bd0ae52f0bec211bcc23117a0aea28726b590cf4471b1250d75940d45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
