# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e50c8e3e9913445f3af7677ce017d56a7898eafdd643a4af2d1e191ab31a656bf76cebf784e7d06bb7ee0c52317948dd9531b5bd1eb21a426815d0b4c5d86a25

test:
  secret_key_base: 542ff80d30af65b555f91fafaa78d3e11d48d7d74b991ed850e421c1d88f91fb702f3b8a24931f313aae8fa752803208b6cc74e680465202f3664e7b3ef6a970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
