# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76ef52dd91f3743ca10027667f97dfb6a09fc3d0d543a7e45679972af2064a81b52b738c19132e28131fc6bfc357237e733d6715b4576636eedd1d75e67cde48

test:
  secret_key_base: a8ca6f1ceaedd2fca732f7b93b698793d9c8df9c04a4ad3f693c3eb43d60669de3732189b01c2a90f71c1569256fc5b52263b2a98b6b2677bacb1445bc19d480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
