# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c6ab538d86fec3b0077d4ae6cf42cfc36c2ff91868db9b8df1cf880640a13ebb32ea9cad65fe24645ada8d35646e7cbeb4cb47c3e9129b3cb2f434b724541f6

test:
  secret_key_base: 2cfaadc7b4d175a7115bd234ae90bc251b7eca51348299f00e42ecf6d486a1c90f1b376c23992c5c8c4a715c1a735f1c48510140d302e54bd304ef1a71ef1493

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
